version: '3.8'
services:
  postgres-postgis:
    image: postgis/postgis:15-3.4
    container_name: smart_city_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: smartcity_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: