export const APP_ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ABOUT: '/about',
  ALL_CITY: '/all-city',
  SERVICE: '/service',
  DISCOVERY: '/discovery',
  VENUE_DETAIL: '/venues/:venueId',
  CITY_MAP: '/city-map',
  TERMS: '/terms',
  FEEDBACK: '/feedback', // Restored FEEDBACK route constant
  ADMIN_DASHBOARD: '/admin',
  ADMIN_BOUNDARIES: '/admin/boundaries',
  ADMIN_USERS: '/admin/users',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_APPROVALS: '/admin/approvals',
  ADMIN_FEEDBACK: '/admin/feedback',
  MERCHANT_DASHBOARD: '/merchant',
  MERCHANT_POSTS: '/merchant/posts',
  MERCHANT_WORKBENCH: '/merchant/workbench',
};
