export const APP_ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ABOUT: '/about',
  ALL_CITY: '/all-city',
  SERVICE: '/service',
  FORUM: '/forum',
  DISCOVERY: '/discovery',
  LANDING_DETAIL: '/landing/:slug',
  PLACE_LIST: '/places',
  SERVICE_DETAIL: '/service-detail/:slug',
  VENUE_DETAIL: '/venues/:venueId',
  CITY_MAP: '/city-map',
  TERMS: '/terms',
  FEEDBACK: '/feedback', // Restored FEEDBACK route constant
  ADMIN_DASHBOARD: '/admin',
  ADMIN_BOUNDARIES: '/admin/boundaries',
  ADMIN_FORUM: '/admin/forum',
  ADMIN_FORUM_REPORTS: '/admin/forum/reports',
  ADMIN_FORUM_VIEW: '/admin/forum/view',
  ADMIN_USERS: '/admin/users',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_PACKAGES: '/admin/packages',
  ADMIN_APPROVALS: '/admin/approvals',
  ADMIN_FEEDBACK: '/admin/feedback',
  MERCHANT_DASHBOARD: '/merchant',
  MERCHANT_POSTS: '/merchant/posts',
  MERCHANT_POST_ADVERTISE: '/merchant/posts/:venueId/advertise',
  MERCHANT_WORKBENCH: '/merchant/workbench',
  MERCHANT_WORKBENCH_EDIT: '/merchant/workbench/:venueId',
};
