-- Smart City Discovery
-- Complete schema expansion based on the current project scope.
-- Safe-first approach:
-- 1. Preserve existing wards and venues tables.
-- 2. Extend them with nullable columns where possible.
-- 3. Add the missing tables needed for admin, merchant, user, AI, and promotion flows.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'user_role'
  ) then
    create type user_role as enum ('admin', 'merchant', 'user');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'account_status'
  ) then
    create type account_status as enum ('active', 'pending', 'banned', 'inactive');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'merchant_verification_status'
  ) then
    create type merchant_verification_status as enum ('draft', 'pending', 'approved', 'rejected');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'venue_status'
  ) then
    create type venue_status as enum ('draft', 'pending', 'approved', 'rejected', 'hidden');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'image_type'
  ) then
    create type image_type as enum ('cover', 'gallery', 'menu', 'business_license');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'report_target_type'
  ) then
    create type report_target_type as enum ('venue', 'review', 'user');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'report_status'
  ) then
    create type report_status as enum ('pending', 'reviewing', 'resolved', 'rejected');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'ad_package_status'
  ) then
    create type ad_package_status as enum ('active', 'inactive');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'ad_booking_status'
  ) then
    create type ad_booking_status as enum ('pending_payment', 'paid', 'running', 'completed', 'cancelled');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'payment_status'
  ) then
    create type payment_status as enum ('pending', 'paid', 'failed', 'refunded');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'ai_request_type'
  ) then
    create type ai_request_type as enum ('recommendation', 'image_recognition');
  end if;

  if not exists (
    select 1
    from pg_type
    where typname = 'category_type'
  ) then
    create type category_type as enum ('cuisine', 'venue_type', 'feature');
  end if;
end $$;

create table if not exists profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text unique,
  full_name text,
  phone text,
  avatar_url text,
  role user_role not null default 'user',
  status account_status not null default 'active',
  is_profile_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists merchant_profiles (
  id bigint generated by default as identity primary key,
  profile_id uuid not null unique references profiles (id) on delete cascade,
  business_name text not null,
  contact_name text,
  contact_phone text,
  business_address text,
  tax_code text,
  license_number text,
  license_image_url text,
  verification_status merchant_verification_status not null default 'draft',
  submitted_at timestamptz,
  approved_at timestamptz,
  rejected_at timestamptz,
  approved_by_profile_id uuid references profiles (id) on delete set null,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists wards
  add column if not exists slug text,
  add column if not exists description text,
  add column if not exists is_active boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists wards_slug_key on wards (slug);
create unique index if not exists wards_ward_id_key on wards (ward_id);

alter table if exists venues
  add column if not exists owner_profile_id uuid references profiles (id) on delete set null,
  add column if not exists merchant_profile_id bigint references merchant_profiles (id) on delete set null,
  add column if not exists slug text,
  add column if not exists description text,
  add column if not exists phone text,
  add column if not exists cover_image_url text,
  add column if not exists business_license_image_url text,
  add column if not exists status venue_status not null default 'pending',
  add column if not exists approved_by_profile_id uuid references profiles (id) on delete set null,
  add column if not exists approved_at timestamptz,
  add column if not exists rejected_at timestamptz,
  add column if not exists rejection_reason text,
  add column if not exists average_rating numeric(3,2) not null default 0,
  add column if not exists total_reviews integer not null default 0,
  add column if not exists is_promoted boolean not null default false,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists venues_slug_key on venues (slug);
create index if not exists venues_owner_profile_id_idx on venues (owner_profile_id);
create index if not exists venues_merchant_profile_id_idx on venues (merchant_profile_id);
create index if not exists venues_status_idx on venues (status);
create index if not exists venues_ward_id_idx on venues (ward_id);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  category_type category_type not null default 'cuisine',
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists venue_categories (
  venue_id int4 not null references venues (id) on delete cascade,
  category_id bigint not null references categories (id) on delete cascade,
  primary key (venue_id, category_id)
);

create table if not exists venue_images (
  id bigint generated by default as identity primary key,
  venue_id int4 not null references venues (id) on delete cascade,
  image_url text not null,
  image_type image_type not null default 'gallery',
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists venue_images_venue_id_idx on venue_images (venue_id);

create table if not exists saved_venues (
  profile_id uuid not null references profiles (id) on delete cascade,
  venue_id int4 not null references venues (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, venue_id)
);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  venue_id int4 not null references venues (id) on delete cascade,
  author_profile_id uuid not null references profiles (id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reviews_venue_id_idx on reviews (venue_id);
create index if not exists reviews_author_profile_id_idx on reviews (author_profile_id);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  reporter_profile_id uuid not null references profiles (id) on delete cascade,
  target_type report_target_type not null,
  reported_venue_id int4 references venues (id) on delete cascade,
  reported_review_id bigint references reviews (id) on delete cascade,
  reported_profile_id uuid references profiles (id) on delete cascade,
  reason text not null,
  status report_status not null default 'pending',
  admin_note text,
  resolved_by_profile_id uuid references profiles (id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists reports_status_idx on reports (status);
create index if not exists reports_venue_target_idx on reports (reported_venue_id);
create index if not exists reports_review_target_idx on reports (reported_review_id);
create index if not exists reports_profile_target_idx on reports (reported_profile_id);

create table if not exists ad_packages (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  duration_hours integer not null,
  priority_level integer not null default 1,
  price numeric(12,2) not null,
  status ad_package_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists ad_bookings (
  id bigint generated by default as identity primary key,
  merchant_profile_id bigint not null references merchant_profiles (id) on delete cascade,
  venue_id int4 not null references venues (id) on delete cascade,
  ad_package_id bigint not null references ad_packages (id) on delete restrict,
  title text,
  status ad_booking_status not null default 'pending_payment',
  start_at timestamptz,
  end_at timestamptz,
  amount numeric(12,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ad_bookings_venue_id_idx on ad_bookings (venue_id);
create index if not exists ad_bookings_status_idx on ad_bookings (status);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  ad_booking_id bigint references ad_bookings (id) on delete set null,
  merchant_profile_id bigint not null references merchant_profiles (id) on delete cascade,
  amount numeric(12,2) not null,
  provider text not null default 'vnpay',
  provider_transaction_id text,
  status payment_status not null default 'pending',
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists payments_merchant_profile_id_idx on payments (merchant_profile_id);
create index if not exists payments_status_idx on payments (status);

create table if not exists weather_snapshots (
  id bigint generated by default as identity primary key,
  ward_id varchar references wards (ward_id) on delete set null,
  latitude float8,
  longitude float8,
  weather_main text,
  weather_description text,
  temperature_c numeric(5,2),
  humidity integer,
  observed_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists weather_snapshots_ward_id_idx on weather_snapshots (ward_id);
create index if not exists weather_snapshots_observed_at_idx on weather_snapshots (observed_at desc);

create table if not exists ai_recommendation_logs (
  id bigint generated by default as identity primary key,
  profile_id uuid references profiles (id) on delete set null,
  ward_id varchar references wards (ward_id) on delete set null,
  weather_snapshot_id bigint references weather_snapshots (id) on delete set null,
  prompt_context jsonb not null default '{}'::jsonb,
  recommended_venue_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists image_recognition_logs (
  id bigint generated by default as identity primary key,
  profile_id uuid references profiles (id) on delete set null,
  image_url text,
  predicted_label text not null,
  confidence numeric(5,4),
  nearby_venue_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists ai_requests (
  id bigint generated by default as identity primary key,
  profile_id uuid references profiles (id) on delete set null,
  request_type ai_request_type not null,
  request_payload jsonb not null default '{}'::jsonb,
  response_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
